version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  server:
    container_name: server
    restart: always
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - "MONGO_URI=${MONGO_URI}"
      - "JWT_SECRET=${TOKEN}"
    links:
      - mongo
  client:
    container_name: client
    restart: always
    build: ./user
    ports:
      - "80:80"
    links:
      - server
  